# Setup
title:        Voto electrónico, un desafío para la democracia
tagline:      Foro sobre Voto Electrónico en la Facultad de Ciencias Económicas, Universidad Nacional de Río Cuarto
baseurl:      "https://pewen.github.io/evoto"
paginate:     1
encoding:     utf-8

# About/contact
author:
  name:       dbellomo
  url:        http://yourhomepage.com 

# Gems
#gems:
#  - jekyll-paginate

#Others
markdown: kramdown
